### ISSUE TITLE
Conda package comes with debug version of `expat` for `msvc2008` build

### ISSUE THREAD

**Issue by seanyen** [conda-forge/expat-feedstock#19]
The latest `expat` package for `msvc2008` comes with `expatd.dll` and `expatd.lib` but not the released version of `expat.dll` and `expat.lib` which could be a problem for downstream projects to consume. It would be great to see it is fixed. Thanks!

Package:
https://anaconda.org/conda-forge/expat/2.2.5/download/win-64/expat-2.2.5-h087d2c9_1003.tar.bz2

**Comment by seanyen** [comment]
https://github.com/conda-forge/apr-feedstock/pull/6

**Comment by ocefpaf** [comment]
@seanyen we are usually lacking people with Windows knowledge. Do you know how to fix that? PRs are welcomed!

**Comment by seanyen** [comment]
@ocefpaf I sent out a PR which should fix it. And let's wait for the CI to see if it is green for all platforms.
